<script lang="ts" setup>
import { onBeforeUnmount, onMounted, ref } from 'vue';
import { useRoute } from 'vue-router';
import { Page } from '@vben/common-ui';
const route = useRoute(); const logs = ref<string[]>([]); const connected = ref(false); const reconnecting = ref(false); const errorMessage = ref(''); const pending: string[] = []; let socket: WebSocket | undefined; let retry = 0; let retryTimer: ReturnType<typeof setTimeout>; let heartbeatTimer: ReturnType<typeof setInterval>; let flushTimer: ReturnType<typeof setTimeout>; const maxLogs = 2000;
const value = (key: string) => String(route.query[key] ?? '');
function append(valueToAdd: unknown) { pending.push(typeof valueToAdd === 'string' ? valueToAdd : JSON.stringify(valueToAdd)); if (!flushTimer) flushTimer = setTimeout(() => { logs.value.push(...pending.splice(0)); if (logs.value.length > maxLogs) logs.value.splice(0, logs.value.length - maxLogs); flushTimer = undefined; }, 50); }
async function getUrl() { if (value('wsUrl')) return value('wsUrl'); try { const config = await (await fetch('/config.json', { cache: 'no-store' })).json(); return config.websocketUrl || ''; } catch { errorMessage.value = '无法读取 /config.json，请配置 websocketUrl'; return ''; } }
function connect(address: string) { if (!address) { errorMessage.value = 'WebSocket 地址为空，请配置 websocketUrl 或传入 wsUrl'; return; } errorMessage.value = ''; try { socket = new WebSocket(address); } catch (error) { errorMessage.value = `WebSocket 地址无效：${String(error)}`; return; } socket.binaryType = 'arraybuffer'; socket.onopen = () => { connected.value = true; reconnecting.value = false; retry = 0; heartbeatTimer = setInterval(() => { if (socket?.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ type: 'ping' })); }, 30000); }; socket.onmessage = async (event) => { if (typeof event.data === 'string') { try { append(JSON.parse(event.data)); } catch { append(event.data); } } else if (event.data instanceof ArrayBuffer) append(new TextDecoder().decode(event.data)); else if (event.data instanceof Blob) append(await event.data.text()); }; socket.onerror = () => { errorMessage.value = 'WebSocket 连接失败，请检查地址、服务端和代理配置'; append('WebSocket connection error'); }; socket.onclose = (event) => { connected.value = false; if (heartbeatTimer) clearInterval(heartbeatTimer); if (event.code !== 1000 && retry < 8) { reconnecting.value = true; retryTimer = setTimeout(() => connect(address), Math.min(1000 * 2 ** retry++, 30000)); } }; }
onMounted(async () => connect(await getUrl()));
onBeforeUnmount(() => { if (retryTimer) clearTimeout(retryTimer); if (heartbeatTimer) clearInterval(heartbeatTimer); if (flushTimer) clearTimeout(flushTimer); socket?.close(1000, 'page closed'); });
</script>
<template><Page title="日志分析"><div class="p-4 space-y-4"><a-card title="日志对象" size="small"><div class="grid grid-cols-2 gap-3 md:grid-cols-4"><div>预算名称：{{ value('budgetName') }}</div><div>预算方广告位ID：{{ value('dspSlotCode') }}</div><div>广告位名称：{{ value('dspSlotName') }}</div><div>媒体广告位ID：{{ value('sspSlotId') }}</div></div></a-card><a-card title="实时日志" size="small"><template #extra><span>{{ connected ? '已连接' : reconnecting ? '重连中' : '未连接' }}</span></template><div v-if="errorMessage" class="mb-2 text-red-500">{{ errorMessage }}</div><pre class="min-h-64 max-h-[60vh] overflow-auto whitespace-pre-wrap bg-gray-950 p-3 text-gray-200">{{ logs.join('\n') }}</pre></a-card></div></Page></template>
